---
- name: Create a text file on the desktop
  hosts: all
  gather_facts: yes
  tasks:
    - name: Create billyg.txt file on desktop
      win_file:
        path: "{{ ansible_env.USERPROFILE }}\\Desktop\\billyg.txt"
        state: touch